# Generated by Django 4.0.5 on 2022-10-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_cover_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('d', 'Draft')], max_length=1, verbose_name="blog's status"),
        ),
    ]
