# Generated by Django 4.0.5 on 2022-09-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_time_created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_time_modified',
            new_name='datetime_modified',
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product_covers/', verbose_name='Product cover'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount on this product'),
        ),
    ]
