# Generated by Django 4.0.5 on 2022-10-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_parent_alter_product_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'id')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
